pipeline {
    agent any

    stages {
        stage('Preparation') { 
            steps {
                git 'https://github.com/Mohamedzonkol/Dev-Ops-Tasks.git'
            }
        }

        stage('Build') {
            steps {
                dir('Task12/spring-petclinic') { 
                    withCredentials([usernamePassword(credentialsId: 'dockerhub', usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD')]) {
                        sh """
                            docker build . -t MohamedElsayed7/Task12
                            docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
                            docker push MohamedElsayed7/Task12
                        """
                    }
                }
            }
        }

        stage('Run') {
            steps {
                dir('Task12/spring-petclinic') { 
                    sh """
                        docker-compose pull
                        docker-compose up -d
                    """
                }
            }
        }
    }

    post {
        always {
            cleanWs()  // Clean workspace after each build
        }
    }
}
