version: '3.8'

services:
  spring-petclinic:
    build: .
    environment:
      - SPRING_PROFILES_ACTIVE=postgres
      - MYSQL_URL=jdbc:mysql://mysql:3306/petclinic
      - MYSQL_USER=petclinic
      - MYSQL_PASS=petclinic
      - POSTGRES_URL=jdbc:postgresql://postgres:5432/petclinic
      - POSTGRES_USER=petclinic
      - POSTGRES_PASS=petclinic
    deploy:
      replicas: 5
      restart_policy:
        condition: on-failure
        delay: 3s
    depends_on:
      - mysql
      - postgres

  mysql:
    image: mysql:8.0
    ports:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

  postgres:
    image: postgres:13
    ports:
      - "5432"
    environment:
      - POSTGRES_USER=petclinic
      - POSTGRES_PASSWORD=petclinic
      - POSTGRES_DB=petclinic
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U petclinic"]
      interval: 30s
      timeout: 10s
      retries: 3
  
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/log:/var/log/nginx
    depends_on:
      - spring-petclinic

volumes:
  mysql_data:
  postgres_data:
