version: '3.8'

services:
  jenkins:
    image: jenkins-dind
    container_name: jenkins
    ports:
      - "8081:8080"
      - "50001:50000"
    volumes:
      - /var/jenkins_Dind:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
